### ISSUE TITLE
Document the correct way to look up LineInfo(s) given only RVA

### ISSUE THREAD

**Issue by Ben-Lichtman** [willglynn/pdb#131]
I've been trying to correctly convert RVA to LineInfo struct(s), however it seems to be a quite roundabout process, and I'm not confident that I've arrived at the most correct / efficient solution:

My current approach is, for each RVA I want to look up the line for (cribbing off the example in the repo):
- Convert the RVA to a PdbInternalSectionOffset
- Iterate through DebugInformation::modules
- For each module I am getting a LineProgram
- Then call lines_for_symbol on the LineProgram with the PdbInternalSectionOffset
- For each line returned by that I am checking if line.offset == the PdbInternalSectionOffset

This multi-nested loop seems to be inefficient and I think is not even returning entirely correct results. Is there a better way?

**Comment by mstange** [comment]
Can you use [pdb-addr2line](https://docs.rs/pdb-addr2line/) instead? It does all of this for you. It also only loads the modules that are needed for the looked-up rvas, and it has multiple layers of caching.

**Comment by mstange** [comment]
I think your list mostly looks good, except for the last item: Not every instruction has a matching line entry with the instruction's offset; some line entries cover multiple instructions. So you need to get the "closest" line entry (line.offset <= probe_offset). And the line entries need to be sorted by offset first.
Furthermore, you may want to handle inlined function calls. If the address is inside a function A that was inlined into a function B, do you want the line number in A or the line number in B where A was called? Your list will give you the latter.

**Comment by Ben-Lichtman** [comment]
I was not aware of this crate, I will give it a try, thanks. I will close this on the assumption that this crate implements the best method for this.
