### ISSUE TITLE
Add an addr2line example

### ISSUE THREAD

**Issue by jrmuizel** [willglynn/pdb#40]
This probably a pretty useful thing to show how to do.

**Comment by jplatte** [comment]
This would be a very useful separate crate, actually. I haven't been able to find a working addr2line for windows anywhere.

**Comment by jrmuizel** [comment]
I posted a somewhat functional version of this in #72

**Comment by luser** [comment]
At some point it'd be great to support the public symbol stream since that lets you do fast lookups by address or name. I refreshed my memory and filed an issue with pointers: https://github.com/willglynn/pdb/issues/82

**Comment by jrmuizel** [comment]
I've expanded https://github.com/willglynn/pdb/pull/72 with some crappy code that has been somewhat usable for me here: https://github.com/jrmuizel/pdb-addr2line

**Comment by Pombal** [comment]
Thanks @jrmuizel, that's very useful.

What are the steps to achieve the same functionality but for every local, member, or global variable as well as functions?

**Comment by mstange** [comment]
@jrmuizel's prototype has now evolved into https://github.com/mstange/pdb-addr2line .
You can use it with `cargo install --examples pdb-addr2line` .

I think this issue (and PR #72) can be closed.

**Comment by jan-auer** [comment]
Awesome, thanks! I think we can link to it from the Readme.
