### ISSUE TITLE
LineProgram::lines_at_offset is pretty slow

### ISSUE THREAD

**Issue by calixteman** [willglynn/pdb#61]
Looking at https://github.com/willglynn/pdb/blob/master/src/modi/c13.rs#L897 it seems that getting all the line info for all the files is quadratic in the number of files.

**Comment by jan-auer** [comment]
Correct. It currently parses all sections over and over again, instead of just once when constructing the line program. 

I have a preliminaty fix for this already, will try to check it in soon.

**Comment by calixteman** [comment]
It'd be nice :)
Using perf I noticed that 20% of the time is spent in this fonction.
