### ISSUE TITLE
Cannot retrieve existing lines with lines_at_offset

### ISSUE THREAD

**Issue by calixteman** [willglynn/pdb#63]
In inspecting a basic PDB (almost a basic helloworld program compiled with clang on windows), there is a proc symbol for _security_check_cookie (the code should be almost this one: https://github.com/adityaramesh/concurrency_runtime/blob/master/VS2013_SP2/crt/src/AMD64/amdsecgs.asm).
The InternalSectionOffset is {s: 0x1, o: 0x8990} but when I try to get line info I got nothing.
The reason is that the InternalSectionOffset for lines is at {s: 0x1, o: 0x8980}.
My hypothesis is that the executable code is really at 0x8990 (line 47) and there are metadata or padding or whatever at 0x8980.
For info, the code_size of the proc is 33 where it appears to be 49 (33 + 16) in DbgLineSub.
So, I'd say that we shouldn't get "lines_section.header.offset == offset" but take the max before offset.
If you need to have the pdb, then I can share it with you.

**Comment by calixteman** [comment]
After thinking about that: if my reasoning is correct, then it means we should keep a sorted Vec of (PdbInternalSectionOffset, DebugSubsection) (sorted on offset) and then make a binary search to get the correct DS.
It should fix in the mean time the complexity of lines_at_offset (which is currently linear) which should become log (I'd have prefer constant but doesn't seem possible).

**Comment by jan-auer** [comment]
We can probably merge this with the fix for https://github.com/willglynn/pdb/issues/61. The fix would be pretty much what you proposed, except I would propose a `BTreeMap<Offset, DS>`.

However, in PDBs there is *always* a separate subsection per function. So if you search for the function's start offset, you should always have an exact hit. What is the offset that you're feeding into `lines_at_offset`? This obviously includes the function epilogue, which might account for the difference of `0x10`.

**Comment by calixteman** [comment]
I used lines_at_offset with proc_symbol.offset (ie: {s: 0x1, o: 0x8990}).
I printed DebugLinesSubsections for this line_program (this is the only one):
DebugLinesSubsection { header: DebugLinesHeader { offset: PdbInternalSectionOffset { section: 0x1, offset: 0x8980 }, flags: 0, code_size: 49 }, data: [0, 0, 0, 0, 9, 0, 0, 0, 84, 0, 0, 0, 16, 0, 0, 0, 45, 0, 0, 128, 16, 0, 0, 0, 47, 0, 0, 128, 23, 0, 0, 0, 48, 0, 0, 128, 26, 0, 0, 0, 49, 0, 0, 128, 30, 0, 0, 0, 50, 0, 0, 128, 35, 0, 0, 0, 51, 0, 0, 128, 38, 0, 0, 0, 52, 0, 0, 128, 40, 0, 0, 0, 62, 0, 0, 128, 44, 0, 0, 0, 66, 0, 0, 128] }

So it seems that it's "almost always" or maybe I'm doing something wrong.
