### ISSUE TITLE
UserDefinedTypeSourceId::source_file field is incorrect type

### ISSUE THREAD

**Issue by camden-smallwood** [willglynn/pdb#95]
The `source_file` field in the `UserDefinedTypeSourceId` struct is of type `IdIndex`, but it should be of type `StringRef`. Currently I have to manually de/reconstruct it by hand. Fortunately the `IdIndex` and `StringRef` types both have public fields and there is a workaround, but this should not be necessary:

https://github.com/willglynn/pdb/blob/3d394eaf547998eeebc7c08ac5788d83d98a1caa/src/tpi/id.rs#L163

```Rust
if let Ok(IdData::UserDefinedTypeSource(udt)) = typ.parse() {
    if let Ok(source_file) = StringRef(udt.source_file.0).to_string_lossy(&string_table) {
        println!("{:?}", source_file);
    }
}
```

**Comment by jan-auer** [comment]
Thanks for the report!

There seems to be a difference between [`LF_UDT_SRC_LINE`](https://github.com/Microsoft/microsoft-pdb/blob/1d60e041600117a5004de84baa960d2c953a6aa6/include%2Fcvinfo.h#L1703) and [`LF_UDT_MOD_SRC_LINE`](https://github.com/Microsoft/microsoft-pdb/blob/1d60e041600117a5004de84baa960d2c953a6aa6/include%2Fcvinfo.h#L1710) that we missed in the initial implementation.

I currently don't have PDBs at hand to verify this, but it looks like we either need to split this into two types, or we create an enum field for the file reference that can either be a `IdIndex` or a `(u16, StringRef)`.
